// Generated by ginue
module.exports = {
  views: {
    活動一覧: {
      type: 'LIST',
      name: '活動一覧',
      id: '5517970',
      filterCond: '',
      sort: '対応日時 desc',
      index: '0',
      fields: ['対応日時', '対応者', '顧客名', '案件名', '対応内容', '商談メモ', '添付ファイル'],
    },
  },
}
