// Generated by ginue
module.exports = {
  layout: [
    {
      type: 'ROW',
      fields: [
        {
          type: 'LABEL',
          label: '<div><b><font color="#0b5394" size="4">活動履歴</font></b></div>',
          size: {
            width: '104',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'RECORD_NUMBER',
          code: 'レコード番号',
          size: {
            width: '120',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'SINGLE_LINE_TEXT',
          code: '顧客名',
          size: {
            width: '326',
          },
        },
        {
          type: 'SINGLE_LINE_TEXT',
          code: '部署名',
          size: {
            width: '161',
          },
        },
        {
          type: 'SINGLE_LINE_TEXT',
          code: '担当者名',
          size: {
            width: '193',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'SINGLE_LINE_TEXT',
          code: '案件名',
          size: {
            width: '326',
          },
        },
        {
          type: 'REFERENCE_TABLE',
          code: '案件詳細',
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'DATE',
          code: '対応日時',
          size: {
            width: '117',
          },
        },
        {
          type: 'DROP_DOWN',
          code: '対応内容',
          size: {
            width: '217',
          },
        },
        {
          type: 'USER_SELECT',
          code: '対応者',
          size: {
            width: '357',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'MULTI_LINE_TEXT',
          code: '商談メモ',
          size: {
            width: '680',
            innerHeight: '148',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'FILE',
          code: '添付ファイル',
          size: {
            width: '207',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'HR',
          size: {
            width: '680',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'NUMBER',
          code: '案件管理レコード番号_関連レコード一覧紐付け用',
          size: {
            width: '372',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'NUMBER',
          code: '顧客管理レコード番号_関連レコード一覧紐付け用',
          size: {
            width: '372',
          },
        },
      ],
    },
  ],
}
