// Generated by ginue
module.exports = {
  rights: [
    {
      filterCond: '対応者 not in (" USER", "akaza")',
      entities: [
        {
          entity: {
            type: 'GROUP',
            code: 'everyone',
          },
          viewable: false,
          editable: false,
          deletable: false,
          includeSubs: false,
        },
      ],
    },
  ],
}
