// Generated by ginue
module.exports = {
  appId: '238',
  code: '',
  name: '[stg]案件管理-devkin',
  description:
    '<div>案件ごとに、受注の確度や金額はもちろん、商談の履歴も記録できるアプリです。</div>   <div>「顧客管理」アプリから、顧客の会社名や担当者名をルックアップして関連付けることができます。</div><div>関連付けた案件のデータは「顧客管理」アプリからも確認できます。</div><div><br /></div><div><div>本アプリは「顧客管理」「活動履歴」と同じく、営業支援パックの構成アプリの一つです。</div><div>営業支援パックの詳細説明は<a href="https://jp.cybozu.help/k/ja/id/040637.html?kin&#61;d&amp;utm_source&#61;product&amp;utm_campaign&#61;sales_crm_pack" target="_blank" rel="nofollow noopener noreferrer">こちらのヘルプページ</a>をご参照ください。</div></div>',
  createdAt: '2024-01-22T15:46:43.000Z',
  creator: {
    code: 'akaza',
    name: 'akaza',
  },
  modifiedAt: '2024-01-22T15:48:59.000Z',
  modifier: {
    code: 'akaza',
    name: 'akaza',
  },
  spaceId: '45',
  threadId: '46',
}
