// Generated by ginue
module.exports = {
  scope: 'ALL',
  desktop: {
    js: ['<DESKTOP_JS>'],
    css: ['<DESKTOP_CSS>'],
  },
  mobile: {
    js: ['<MOBILE_JS>'],
    css: ['<MOBILE_CSS>'],
  },
}
