// Generated by ginue
module.exports = {
  scope: 'ALL',
  desktop: {
    js: [
      {
        type: 'URL',
        url: 'https://localhost:59000/project.js',
      },
    ],
    css: [],
  },
  mobile: {
    js: [],
    css: [],
  },
}
