// Generated by ginue
module.exports = {
  layout: [
    {
      type: 'ROW',
      fields: [
        {
          type: 'LABEL',
          label: '<div><font color="#0b5394" size="4"><b style="">案件情報</b></font></div>',
          size: {
            width: '140',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'RECORD_NUMBER',
          code: 'レコード番号',
          size: {
            width: '120',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'SINGLE_LINE_TEXT',
          code: '顧客名',
          size: {
            width: '350',
          },
        },
        {
          type: 'SINGLE_LINE_TEXT',
          code: '部署名',
          size: {
            width: '142',
          },
        },
        {
          type: 'SINGLE_LINE_TEXT',
          code: '担当者名',
          size: {
            width: '259',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'SINGLE_LINE_TEXT',
          code: '案件名',
          size: {
            width: '492',
          },
        },
        {
          type: 'DROP_DOWN',
          code: '確度',
          size: {
            width: '140',
          },
        },
        {
          type: 'DATE',
          code: '初回商談日',
          size: {
            width: '117',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'DROP_DOWN',
          code: '提案プラン',
          size: {
            width: '204',
          },
        },
        {
          type: 'MULTI_SELECT',
          code: 'オプション',
          size: {
            width: '198',
          },
        },
        {
          type: 'USER_SELECT',
          code: '商談担当者',
          size: {
            width: '344',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'NUMBER',
          code: 'プラン費用',
          size: {
            width: '149',
          },
        },
        {
          type: 'NUMBER',
          code: 'オプション費用',
          size: {
            width: '149',
          },
        },
        {
          type: 'CALC',
          code: '合計費用',
          size: {
            width: '191',
          },
        },
        {
          type: 'DATE',
          code: '受注予定日',
          size: {
            width: '119',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'MULTI_LINE_TEXT',
          code: '詳細',
          size: {
            width: '746',
            innerHeight: '84',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'FILE',
          code: '資料',
          size: {
            width: '207',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'REFERENCE_TABLE',
          code: '案件に紐付く活動履歴',
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'HR',
          size: {
            width: '746',
          },
        },
      ],
    },
    {
      type: 'ROW',
      fields: [
        {
          type: 'NUMBER',
          code: '顧客管理レコード番号_関連レコード紐付け用',
          size: {
            width: '344',
          },
        },
      ],
    },
  ],
}
