// Generated by ginue
module.exports = {
  views: {
    顧客一覧: {
      type: 'LIST',
      name: '顧客一覧',
      id: '2031',
      filterCond: '',
      sort: '作成日時 desc',
      index: '0',
      fields: ['顧客名', '部署名', 'TEL', 'メールアドレス', '郵便番号', '住所'],
    },
  },
}
