// Generated by ginue
module.exports = {
  appId: '<APP_ID>',
  code: '',
  name: '<APP_NAME>',
  description:
    '<div>顧客名、担当者名、連絡先などお客様の情報を登録するアプリです。</div>    <div>また、このアプリの会社名と合致する「案件情報」アプリのレコード一覧を表示することができるので、</div><div>あるお客様の顧客情報と、その案件を1画面でまとめて確認できます。</div><div><br /></div><div><div>本アプリは「案件管理」「活動履歴」と同じく、営業支援パックの構成アプリの一つです。</div><div>営業支援パックの詳細説明は<a href="https://jp.cybozu.help/k/ja/id/040637.html?kin&#61;d&amp;utm_source&#61;product&amp;utm_campaign&#61;sales_crm_pack" target="_blank" rel="nofollow noopener noreferrer">こちらのヘルプページ</a>をご参照ください。</div></div>',
  createdAt: '<CREATED_AT>',
  creator: {
    code: '<CREATOR_CODE>',
    name: '<CREATOR_NAME>',
  },
  modifiedAt: '<MODIFIED_AT>',
  modifier: {
    code: '<MODIFIER_CODE>',
    name: '<MODIFIER_NAME>',
  },
  spaceId: '<SPACE_ID>',
  threadId: '<THREAD_ID>',
}
